name: 🚀 Deploy Backend Api on push

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Checkout latest code
      uses: actions/checkout@v3

    - name: Set up Python Env
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: 🔨 Install dependecies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        echo "FTP Server: $FTP_SERVER"
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: FTP
        # local-dir: ./dist/
        # hello world again
