<<<<<<< HEAD
=======
name: 🚀 Deploy Backend Api on push

>>>>>>> flask
on: 
  push:
    branches:
      - flask
<<<<<<< HEAD
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
=======

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Checkout latest code
      uses: actions/checkout@v3

    - name: Set up Python Env
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: 🔨 Install dependecies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
>>>>>>> flask
        echo "FTP Server: $FTP_SERVER"
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: FTP
<<<<<<< HEAD
        local-dir: ./dist/
=======
        # local-dir: ./dist/
        # hello world again
>>>>>>> flask
